spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/taskdb
    username: postgres
    password: 
    hikari.data-source-properties:
      ssl: true
      sslmode: allow
      sslprotocol: TLSv1.2

  jpa:
    hibernate:
      ddl-auto: update
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
         current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
         dialect: org.hibernate.dialect.PostgreSQLDialect